-- Intended Approach

-- SELECT PRICE AS 'SUM,COUNT,AVG PRICE 보기' FROM PRODUCTS
--WHERE PRICE = (SELECT SUM(PRICE) FROM PRODUCTS
--				WHERE CategoryID = (1,2,3)
--GROUP BY CategoryID;



-- Correct Approach

SELECT SUM(PRICE), COUNT(PRICE), AVG(PRICE) FROM Products
GROUP BY CategoryID
ORDER BY CategoryID DESC;
