-- Intended Approach

-- SELECT PRICE AS 'SUM,COUNT,AVG PRICE 보기' FROM PRODUCTS
--WHERE PRICE = (SELECT SUM(PRICE) FROM PRODUCTS
--				WHERE CategoryID = (1,2,3)
--GROUP BY CategoryID;



-- Correct Approach

SELECT SUM(PRODUCTS), COUNT(PRODUCTS), AVG(PRODUCTS) FROM PRODUCTS
GROUP BY CategoryID