
CREATE TABLE ANSWER
(
  ANSWER_CODE INT          NOT NULL,
  ANSWERS     VARCHAR(200) NULL    ,
  PRIMARY KEY (ANSWER_CODE)
);

CREATE TABLE IDENTIFICATION
(
  ID_CODE                INT          NOT NULL,
  PERSONAL_CUSTOMER_NAME VARCHAR(200) NULL    ,
  PRIMARY KEY (ID_CODE)
);

CREATE TABLE QUESTIONARIES
(
  QUESTION_CODE INT          NOT NULL,
  QUESTIONS     VARCHAR(200) NULL    ,
  PRIMARY KEY (QUESTION_CODE)
);

CREATE TABLE SURVEY_RESULT
(
  ID_CODE       INT NOT NULL,
  QUESTION_CODE INT NOT NULL,
  ANSWER_CODE   INT NOT NULL
);

ALTER TABLE SURVEY_RESULT
  ADD CONSTRAINT FK_IDENTIFICATION_TO_SURVEY_RESULT
    FOREIGN KEY (ID_CODE)
    REFERENCES IDENTIFICATION (ID_CODE);

ALTER TABLE SURVEY_RESULT
  ADD CONSTRAINT FK_QUESTIONARIES_TO_SURVEY_RESULT
    FOREIGN KEY (QUESTION_CODE)
    REFERENCES QUESTIONARIES (QUESTION_CODE);

ALTER TABLE SURVEY_RESULT
  ADD CONSTRAINT FK_ANSWER_TO_SURVEY_RESULT
    FOREIGN KEY (ANSWER_CODE)
    REFERENCES ANSWER (ANSWER_CODE);
