

-- [Attempted Approach]
--SELECT ANIMAL_TYPE,NAME,SEX_UPON_INTAKE FROM ANIMAL_INS
--WHERE NAME IS NULL AS 'No Name'

-- [Corrected Approach]



SELECT ANIMAL-TYPE,
    IF(NAME IS NULL, "No Name", NAME),SEX_UPON_INTAKE
FROM ANIMAL_INS
ORDER BY ANIMAL_ID;